services:
  - type: web
    name: werket
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.prod
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: werket-q5pm.onrender.com,werket.onrender.com,localhost
      - key: CSRF_TRUSTED_ORIGINS
        value: https://werket-q5pm.onrender.com,https://werket.onrender.com
      - key: DEBUG
        value: "false"
      - key: SECURE_SSL_REDIRECT
        value: "false"