services:
  - type: web
    name: werket
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.prod
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: '*'
      - key: CORS_ALLOWED_ORIGINS
        value: https://werket.onrender.com,https://werket-q5pm.onrender.com,capacitor://localhost,http://localhost,https://localhost,app://werket
      - key: CSRF_TRUSTED_ORIGINS
        value: https://werket-q5pm.onrender.com,https://werket.onrender.com,capacitor://localhost,http://localhost,https://localhost,app://werket
      - key: DEBUG
        value: "false"
      - key: SECURE_SSL_REDIRECT
        value: "false"
      - key: DATABASE_URL
        fromDatabase:
          name: werket-db
          property: connectionString
      - key: PYTHONUNBUFFERED
        value: "1"

databases:
  - name: werket-db
    plan: free
    databaseName: werket
    user: werket
